name: Hotfix Delivery (manual versioning and deployment)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to build should have'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    ## Build with maven
    - name: Prepare maven settings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml 

    - name: Set version
      id: version
      run: |
        echo Releasing as ${{ github.event.inputs.version }}
        mvn versions:set -DnewVersion=${{ github.event.inputs.version}}

    - name: Perform build
      run: mvn -B package --file pom.xml

    ## Deploy
    - name: Deploy package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        REPOSITORY_USERID: ${{ secrets.REPOSITORY_USERID }}
        REPOSITORY_CREDENTIALS: ${{ secrets.REPOSITORY_CREDENTIALS }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>neverpile</id><username>${REPOSITORY_USERID}</username><password>${REPOSITORY_CREDENTIALS}</password></server></servers></settings>" > ~/.m2/settings.xml 
        mvn deploy -Dmaven.test.skip.exec=true -DaltDeploymentRepository=neverpile::default::${REPOSITORY_URL}
